/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:a5470ef4-3cd4-466c-9053-e844862512b7",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_ZZAkkTLr6",
    "aws_user_pools_web_client_id": "7ir6pigo87qo2aegoept6h5k03",
    "oauth": {}
};


export default awsmobile;
